version: '2'
services:
    itehproject-app:
        image: itehproject
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://itehproject-mysql:3306/itehproject?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=itehproject-elasticsearch:9300
        ports:
            - 8080:8080
    itehproject-mysql:
        extends:
            file: mysql.yml
            service: itehproject-mysql
    itehproject-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: itehproject-elasticsearch
